_commit: v0.0.52
_src_path: gh:serious-scaffold/ss-python
author_email: nsyntych@punkops.dev
author_name: Nick Syntychakis
copyright_holder: PunkOps
copyright_license: Mozilla Public License 2.0 (MPL 2.0)
copyright_year: '2024'
coverage_threshold: 0
default_py: '3.11'
development_status: Alpha
max_py: '3.12'
min_py: '3.11'
module_name: statebot
organization_name: PunkOps
package_name: statebot
platforms:
- macos
- ubuntu
- windows
project_description: A simple bot using available API to try recreate terraform code
    along with its state from cloud APIs
project_name: Statebot
readme_content: '## A multiline README content here


    '
repo_name: statebot
repo_namespace: punkops
repo_platform: github
